apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: {{ include "pg-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ include "pg-chart.fullname" . }}
