apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: lab1-rs-service
spec:
    replicas: 2
    selector:
       matchLabels:
          app: lab1-app
    template:
       metadata:
          labels:
             app: lab1-app
       spec:
          containers:
          - name: lab1-app
            image: psavchenko/otus-lab1:v1
            ports:
              - containerPort: 8000
