apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
         
                 
spec:
  serviceName: "postgres"
  replicas: 1

  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
                        
        - containerPort: 5432
          name: postgredb
        env:
        - name: POSTGRES_DB
          valueFrom:
              configMapKeyRef:
                name: pg-config
                key: postgres.db
        - name: POSTGRES_USER
          valueFrom:
              configMapKeyRef:
                name: pg-config
                key: postgres.user
        - name: POSTGRES_PASSWORD
          valueFrom:
              secretKeyRef:
                name: pg-secrets
                key: postgres.password
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
